# Generated by Django 4.1.13 on 2024-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
